// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auction_usecase

import (
	"context"
	"fullcycle-auction_go/internal/entity/bid_entity"
	"fullcycle-auction_go/internal/internal_error"

	mock "github.com/stretchr/testify/mock"
)

// newMockbidRepositoryInterface creates a new instance of mockbidRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockbidRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockbidRepositoryInterface {
	mock := &mockbidRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockbidRepositoryInterface is an autogenerated mock type for the bidRepositoryInterface type
type mockbidRepositoryInterface struct {
	mock.Mock
}

type mockbidRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockbidRepositoryInterface) EXPECT() *mockbidRepositoryInterface_Expecter {
	return &mockbidRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CreateBid provides a mock function for the type mockbidRepositoryInterface
func (_mock *mockbidRepositoryInterface) CreateBid(ctx context.Context, bidEntities []bid_entity.Bid) *internal_error.InternalError {
	ret := _mock.Called(ctx, bidEntities)

	if len(ret) == 0 {
		panic("no return value specified for CreateBid")
	}

	var r0 *internal_error.InternalError
	if returnFunc, ok := ret.Get(0).(func(context.Context, []bid_entity.Bid) *internal_error.InternalError); ok {
		r0 = returnFunc(ctx, bidEntities)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal_error.InternalError)
		}
	}
	return r0
}

// mockbidRepositoryInterface_CreateBid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBid'
type mockbidRepositoryInterface_CreateBid_Call struct {
	*mock.Call
}

// CreateBid is a helper method to define mock.On call
//   - ctx context.Context
//   - bidEntities []bid_entity.Bid
func (_e *mockbidRepositoryInterface_Expecter) CreateBid(ctx any, bidEntities any) *mockbidRepositoryInterface_CreateBid_Call {
	return &mockbidRepositoryInterface_CreateBid_Call{Call: _e.mock.On("CreateBid", ctx, bidEntities)}
}

func (_c *mockbidRepositoryInterface_CreateBid_Call) Run(run func(ctx context.Context, bidEntities []bid_entity.Bid)) *mockbidRepositoryInterface_CreateBid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []bid_entity.Bid
		if args[1] != nil {
			arg1 = args[1].([]bid_entity.Bid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbidRepositoryInterface_CreateBid_Call) Return(internalError *internal_error.InternalError) *mockbidRepositoryInterface_CreateBid_Call {
	_c.Call.Return(internalError)
	return _c
}

func (_c *mockbidRepositoryInterface_CreateBid_Call) RunAndReturn(run func(ctx context.Context, bidEntities []bid_entity.Bid) *internal_error.InternalError) *mockbidRepositoryInterface_CreateBid_Call {
	_c.Call.Return(run)
	return _c
}

// FindBidByAuctionId provides a mock function for the type mockbidRepositoryInterface
func (_mock *mockbidRepositoryInterface) FindBidByAuctionId(ctx context.Context, auctionId string) ([]bid_entity.Bid, *internal_error.InternalError) {
	ret := _mock.Called(ctx, auctionId)

	if len(ret) == 0 {
		panic("no return value specified for FindBidByAuctionId")
	}

	var r0 []bid_entity.Bid
	var r1 *internal_error.InternalError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]bid_entity.Bid, *internal_error.InternalError)); ok {
		return returnFunc(ctx, auctionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []bid_entity.Bid); ok {
		r0 = returnFunc(ctx, auctionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bid_entity.Bid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *internal_error.InternalError); ok {
		r1 = returnFunc(ctx, auctionId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*internal_error.InternalError)
		}
	}
	return r0, r1
}

// mockbidRepositoryInterface_FindBidByAuctionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBidByAuctionId'
type mockbidRepositoryInterface_FindBidByAuctionId_Call struct {
	*mock.Call
}

// FindBidByAuctionId is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionId string
func (_e *mockbidRepositoryInterface_Expecter) FindBidByAuctionId(ctx any, auctionId any) *mockbidRepositoryInterface_FindBidByAuctionId_Call {
	return &mockbidRepositoryInterface_FindBidByAuctionId_Call{Call: _e.mock.On("FindBidByAuctionId", ctx, auctionId)}
}

func (_c *mockbidRepositoryInterface_FindBidByAuctionId_Call) Run(run func(ctx context.Context, auctionId string)) *mockbidRepositoryInterface_FindBidByAuctionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbidRepositoryInterface_FindBidByAuctionId_Call) Return(bids []bid_entity.Bid, internalError *internal_error.InternalError) *mockbidRepositoryInterface_FindBidByAuctionId_Call {
	_c.Call.Return(bids, internalError)
	return _c
}

func (_c *mockbidRepositoryInterface_FindBidByAuctionId_Call) RunAndReturn(run func(ctx context.Context, auctionId string) ([]bid_entity.Bid, *internal_error.InternalError)) *mockbidRepositoryInterface_FindBidByAuctionId_Call {
	_c.Call.Return(run)
	return _c
}

// FindWinningBidByAuctionId provides a mock function for the type mockbidRepositoryInterface
func (_mock *mockbidRepositoryInterface) FindWinningBidByAuctionId(ctx context.Context, auctionId string) (*bid_entity.Bid, *internal_error.InternalError) {
	ret := _mock.Called(ctx, auctionId)

	if len(ret) == 0 {
		panic("no return value specified for FindWinningBidByAuctionId")
	}

	var r0 *bid_entity.Bid
	var r1 *internal_error.InternalError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*bid_entity.Bid, *internal_error.InternalError)); ok {
		return returnFunc(ctx, auctionId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *bid_entity.Bid); ok {
		r0 = returnFunc(ctx, auctionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bid_entity.Bid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *internal_error.InternalError); ok {
		r1 = returnFunc(ctx, auctionId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*internal_error.InternalError)
		}
	}
	return r0, r1
}

// mockbidRepositoryInterface_FindWinningBidByAuctionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindWinningBidByAuctionId'
type mockbidRepositoryInterface_FindWinningBidByAuctionId_Call struct {
	*mock.Call
}

// FindWinningBidByAuctionId is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionId string
func (_e *mockbidRepositoryInterface_Expecter) FindWinningBidByAuctionId(ctx any, auctionId any) *mockbidRepositoryInterface_FindWinningBidByAuctionId_Call {
	return &mockbidRepositoryInterface_FindWinningBidByAuctionId_Call{Call: _e.mock.On("FindWinningBidByAuctionId", ctx, auctionId)}
}

func (_c *mockbidRepositoryInterface_FindWinningBidByAuctionId_Call) Run(run func(ctx context.Context, auctionId string)) *mockbidRepositoryInterface_FindWinningBidByAuctionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockbidRepositoryInterface_FindWinningBidByAuctionId_Call) Return(bid *bid_entity.Bid, internalError *internal_error.InternalError) *mockbidRepositoryInterface_FindWinningBidByAuctionId_Call {
	_c.Call.Return(bid, internalError)
	return _c
}

func (_c *mockbidRepositoryInterface_FindWinningBidByAuctionId_Call) RunAndReturn(run func(ctx context.Context, auctionId string) (*bid_entity.Bid, *internal_error.InternalError)) *mockbidRepositoryInterface_FindWinningBidByAuctionId_Call {
	_c.Call.Return(run)
	return _c
}
