// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auction_usecase

import (
	"context"
	"fullcycle-auction_go/internal/entity/auction_entity"
	"fullcycle-auction_go/internal/internal_error"

	mock "github.com/stretchr/testify/mock"
)

// newMockauctionRepositoryInterface creates a new instance of mockauctionRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockauctionRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockauctionRepositoryInterface {
	mock := &mockauctionRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockauctionRepositoryInterface is an autogenerated mock type for the auctionRepositoryInterface type
type mockauctionRepositoryInterface struct {
	mock.Mock
}

type mockauctionRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockauctionRepositoryInterface) EXPECT() *mockauctionRepositoryInterface_Expecter {
	return &mockauctionRepositoryInterface_Expecter{mock: &_m.Mock}
}

// CreateAuction provides a mock function for the type mockauctionRepositoryInterface
func (_mock *mockauctionRepositoryInterface) CreateAuction(ctx context.Context, auctionEntity *auction_entity.Auction) *internal_error.InternalError {
	ret := _mock.Called(ctx, auctionEntity)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuction")
	}

	var r0 *internal_error.InternalError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auction_entity.Auction) *internal_error.InternalError); ok {
		r0 = returnFunc(ctx, auctionEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal_error.InternalError)
		}
	}
	return r0
}

// mockauctionRepositoryInterface_CreateAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuction'
type mockauctionRepositoryInterface_CreateAuction_Call struct {
	*mock.Call
}

// CreateAuction is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionEntity *auction_entity.Auction
func (_e *mockauctionRepositoryInterface_Expecter) CreateAuction(ctx any, auctionEntity any) *mockauctionRepositoryInterface_CreateAuction_Call {
	return &mockauctionRepositoryInterface_CreateAuction_Call{Call: _e.mock.On("CreateAuction", ctx, auctionEntity)}
}

func (_c *mockauctionRepositoryInterface_CreateAuction_Call) Run(run func(ctx context.Context, auctionEntity *auction_entity.Auction)) *mockauctionRepositoryInterface_CreateAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auction_entity.Auction
		if args[1] != nil {
			arg1 = args[1].(*auction_entity.Auction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockauctionRepositoryInterface_CreateAuction_Call) Return(internalError *internal_error.InternalError) *mockauctionRepositoryInterface_CreateAuction_Call {
	_c.Call.Return(internalError)
	return _c
}

func (_c *mockauctionRepositoryInterface_CreateAuction_Call) RunAndReturn(run func(ctx context.Context, auctionEntity *auction_entity.Auction) *internal_error.InternalError) *mockauctionRepositoryInterface_CreateAuction_Call {
	_c.Call.Return(run)
	return _c
}

// FindAuctionById provides a mock function for the type mockauctionRepositoryInterface
func (_mock *mockauctionRepositoryInterface) FindAuctionById(ctx context.Context, id string) (*auction_entity.Auction, *internal_error.InternalError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindAuctionById")
	}

	var r0 *auction_entity.Auction
	var r1 *internal_error.InternalError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auction_entity.Auction, *internal_error.InternalError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auction_entity.Auction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auction_entity.Auction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *internal_error.InternalError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*internal_error.InternalError)
		}
	}
	return r0, r1
}

// mockauctionRepositoryInterface_FindAuctionById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAuctionById'
type mockauctionRepositoryInterface_FindAuctionById_Call struct {
	*mock.Call
}

// FindAuctionById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *mockauctionRepositoryInterface_Expecter) FindAuctionById(ctx any, id any) *mockauctionRepositoryInterface_FindAuctionById_Call {
	return &mockauctionRepositoryInterface_FindAuctionById_Call{Call: _e.mock.On("FindAuctionById", ctx, id)}
}

func (_c *mockauctionRepositoryInterface_FindAuctionById_Call) Run(run func(ctx context.Context, id string)) *mockauctionRepositoryInterface_FindAuctionById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockauctionRepositoryInterface_FindAuctionById_Call) Return(auction *auction_entity.Auction, internalError *internal_error.InternalError) *mockauctionRepositoryInterface_FindAuctionById_Call {
	_c.Call.Return(auction, internalError)
	return _c
}

func (_c *mockauctionRepositoryInterface_FindAuctionById_Call) RunAndReturn(run func(ctx context.Context, id string) (*auction_entity.Auction, *internal_error.InternalError)) *mockauctionRepositoryInterface_FindAuctionById_Call {
	_c.Call.Return(run)
	return _c
}

// FindAuctions provides a mock function for the type mockauctionRepositoryInterface
func (_mock *mockauctionRepositoryInterface) FindAuctions(ctx context.Context, status auction_entity.AuctionStatus, category string, productName string) ([]auction_entity.Auction, *internal_error.InternalError) {
	ret := _mock.Called(ctx, status, category, productName)

	if len(ret) == 0 {
		panic("no return value specified for FindAuctions")
	}

	var r0 []auction_entity.Auction
	var r1 *internal_error.InternalError
	if returnFunc, ok := ret.Get(0).(func(context.Context, auction_entity.AuctionStatus, string, string) ([]auction_entity.Auction, *internal_error.InternalError)); ok {
		return returnFunc(ctx, status, category, productName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auction_entity.AuctionStatus, string, string) []auction_entity.Auction); ok {
		r0 = returnFunc(ctx, status, category, productName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auction_entity.Auction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auction_entity.AuctionStatus, string, string) *internal_error.InternalError); ok {
		r1 = returnFunc(ctx, status, category, productName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*internal_error.InternalError)
		}
	}
	return r0, r1
}

// mockauctionRepositoryInterface_FindAuctions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAuctions'
type mockauctionRepositoryInterface_FindAuctions_Call struct {
	*mock.Call
}

// FindAuctions is a helper method to define mock.On call
//   - ctx context.Context
//   - status auction_entity.AuctionStatus
//   - category string
//   - productName string
func (_e *mockauctionRepositoryInterface_Expecter) FindAuctions(ctx any, status any, category any, productName any) *mockauctionRepositoryInterface_FindAuctions_Call {
	return &mockauctionRepositoryInterface_FindAuctions_Call{Call: _e.mock.On("FindAuctions", ctx, status, category, productName)}
}

func (_c *mockauctionRepositoryInterface_FindAuctions_Call) Run(run func(ctx context.Context, status auction_entity.AuctionStatus, category string, productName string)) *mockauctionRepositoryInterface_FindAuctions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auction_entity.AuctionStatus
		if args[1] != nil {
			arg1 = args[1].(auction_entity.AuctionStatus)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockauctionRepositoryInterface_FindAuctions_Call) Return(auctions []auction_entity.Auction, internalError *internal_error.InternalError) *mockauctionRepositoryInterface_FindAuctions_Call {
	_c.Call.Return(auctions, internalError)
	return _c
}

func (_c *mockauctionRepositoryInterface_FindAuctions_Call) RunAndReturn(run func(ctx context.Context, status auction_entity.AuctionStatus, category string, productName string) ([]auction_entity.Auction, *internal_error.InternalError)) *mockauctionRepositoryInterface_FindAuctions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAuction provides a mock function for the type mockauctionRepositoryInterface
func (_mock *mockauctionRepositoryInterface) UpdateAuction(ctx context.Context, auctionEntity *auction_entity.Auction) *internal_error.InternalError {
	ret := _mock.Called(ctx, auctionEntity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAuction")
	}

	var r0 *internal_error.InternalError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auction_entity.Auction) *internal_error.InternalError); ok {
		r0 = returnFunc(ctx, auctionEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*internal_error.InternalError)
		}
	}
	return r0
}

// mockauctionRepositoryInterface_UpdateAuction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAuction'
type mockauctionRepositoryInterface_UpdateAuction_Call struct {
	*mock.Call
}

// UpdateAuction is a helper method to define mock.On call
//   - ctx context.Context
//   - auctionEntity *auction_entity.Auction
func (_e *mockauctionRepositoryInterface_Expecter) UpdateAuction(ctx any, auctionEntity any) *mockauctionRepositoryInterface_UpdateAuction_Call {
	return &mockauctionRepositoryInterface_UpdateAuction_Call{Call: _e.mock.On("UpdateAuction", ctx, auctionEntity)}
}

func (_c *mockauctionRepositoryInterface_UpdateAuction_Call) Run(run func(ctx context.Context, auctionEntity *auction_entity.Auction)) *mockauctionRepositoryInterface_UpdateAuction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auction_entity.Auction
		if args[1] != nil {
			arg1 = args[1].(*auction_entity.Auction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockauctionRepositoryInterface_UpdateAuction_Call) Return(internalError *internal_error.InternalError) *mockauctionRepositoryInterface_UpdateAuction_Call {
	_c.Call.Return(internalError)
	return _c
}

func (_c *mockauctionRepositoryInterface_UpdateAuction_Call) RunAndReturn(run func(ctx context.Context, auctionEntity *auction_entity.Auction) *internal_error.InternalError) *mockauctionRepositoryInterface_UpdateAuction_Call {
	_c.Call.Return(run)
	return _c
}
